# -*- coding: utf-8 -*-
"""container.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_xQT7xmL7p3XKFMj1nIbBJDixFVvsORm

#<b> <font color='blue'>吳南烈 容器作業

---

#<b>練習01 ~~串列 </b>
串列-list 中可以放什麼?
ans: 字元, 字串, 數字  這是最常見的
<font color='red'>此外, 串列中也可以放入串列 </font>

##<b>數字串列
"""

a_list=[1,4,5,8,9,10]
type(a_list)
print(a_list[1])
print(a_list[6])  #index out of number

"""##<b>文字串列"""

str_list=['p','y','t','h','o','n']
print(str_list)
str_list[0]

"""##<b>字串轉成串列"""

# 字串經過split()處理後的型態，就變成串列
str_msg="I love Python"
b_list=str_msg.split() 
print(b_list)
print(b_list[1],b_list[2])
type(b_list)

"""##<b>將字串拆成字母"""

#將一個字串拆成字元以組成串列,使用list()函數即可
str_msg="I love Python"
c_list=list(str_msg)  #字串轉成串列
print(c_list)
type(c_list)

"""##<b>串列中放串列"""

#串列可以存放不同資料型態,也可以有其他的串列
k1=['book',10]
k2=['campus',15]
k3=['cook',9]
k4=['Python',26]
keywords=[k1,k2,k3,k4] # 4*2陣列
print(keywords)
print(keywords[2])    #index=2, 第二列
print(keywords[2][0]) # row=2,colum=0 
print(keywords[2][1]) # row=2,colum=1

"""##<b>串列其它操作"""

'Python' in k1

'Python' in k4

'Python' in keywords

['Python',26] in keywords

keywords+k1+k2

"""#<b>練習02~~Dict字典
<font color='blue'>改用key為索引,對於文字查詢與應用更為方便

##<b>建立字典
"""

a={'a':1,'b':2} #a 是一個字典(dict)
type (a)

keywords={} #空字典
keywords['book']=10
keywords['campus']=15
keywords['cook']=9
keywords['Python']=26
type(keywords)
print(keywords['Python'])
print(keywords)    #印出字典

#建立字典
week_={'Mon.':'星期一' ,'Tue.':'星期二', 'Wed.':'星期三',\
  'Thur.':'星期四', 'Fri.':'星期五' , \
  'Sat.':'星期六', 'Sun.':'星期日'}
print (week_)
print (week_.keys())
print (week_.values())

week=dict() #建立字典的另一種方式
week['Mon.']='星期一'
week['Tue.']='星期二'
week['Wed.']='星期三'
week['Thur.']='星期四'
week['Fri.']='星期五'
week['Sat.']='星期六'
week['Sun.']='星期日'
week
#-------------------------------
print(week['Fri.'])
print(week.keys())
print(week.values())

"""#<b>練習03~~ set 集合

"""

a={}  #這是字典,不是空集合
type (a)

b={1,2,3,4,5} #b為集合
type(b)

c=set() #c為集合變數
type(c)

"""<b> 數學上的集合運算有「and」「or」「XOR」，
在Python中分別對應符號 「&」「|」「^」
"""

a={1,2,3,4,5}
b={1,3,5,7,9}

a&b   #交集

a|b #聯集

a^b  #a與b不同的元素, XOR

a-b #差集

"""#**問題1**

<h3><b>請撰寫一程式，讓使用者輸入52張牌中的5張，計算並輸出其總和
 *提示: J、Q、K及A 分別代表11、12、13、14 </b>
<pre>
輸入: 5張牌數  
輸出: 5張牌的數值總和
"""

#請撰寫一程式，讓使用者輸入52張牌中的5張，計算並輸出其總和
# *提示: J、Q、K及A 分別代表11、12、13、14
cards =[]
result =0
for i in range(5):
  cards.append(input())
 
for i in range(5):
  if cards[i]=='A': result +=1
  elif cards[i]=='J': result +=11
  elif cards[i]=='Q': result +=12
  elif cards[i]=='K': result +=13
  elif cards[i]=='10': result +=10
  else:
    result +=eval(cards[i])   #  串列中的資料加總
 
print(result)

"""#**問題2**

<b><h3>  以大樂透電腦選號來探討有關串列程式的撰寫  
請撰寫一程式，以亂數產生六個1~49的亂數 </b>
"""

import random 
lotto=[] #亂數函數產生的資料串列
n=1
while n<=6:
  randNum=random.randint(1,49)
  if randNum not in lotto:
    lotto.append(randNum)
    n+=1

print("The lottery numbers are:\n",end='')
for i in lotto:
  print('%4d'%(i),end=' ')
print()
#----------sorting-------------------------------------
lotto.sort()    # 序列排序
print('After sorting:')
for i in lotto:
  print('%4d'%(i),end=' ')
print()

"""#**問題3**

<h3><b>請寫一程式，輸入數個整數並儲存至集合，以輸入-9999為結束點(集合中不含-9999)，最後顯示該集合的長度(Length)、最大值(Max)、最小值(Min)、總和 (Sum) </b>
"""

num=set()
while True:
  inp= eval(input("輸入整數(-9999為結束點):"))
  if inp== -9999:
    break
  num.add(inp)      #加入此數到集合num

print("Length:", len(num))
print("Max:",max(num))
print("Min:",min(num))
print("Sum:",sum(num))

"""#<b>問題4

<b><h3>旅遊地點調查實例。  
目的: 練習如何將資料存入字典及輸出  </b> <br><h4>
輸入: 名字及旅遊地點，然後存入<strong>survey_dict 字典, key: name, value:</strong> <br> travel_location。 輸入完程式會詢問是否有人要輸入。 <br>
輸出：程式結束前會輸出調查結果
"""

survey_dict = {}                        # 建立市場調查空字典
market_survey = True                    # 設定迴圈布林值     

# 讀取參加市場調查者姓名和夢幻旅遊景點
while market_survey:
    name = input("\n請輸入姓名  : ")
    travel_location = input("夢幻旅遊景點: ")
# 將輸入存入survey_dict字典
    survey_dict[name] = travel_location
# 可由此決定是否離開市場調查
    repeat = input("是否有人要參加市場調查?(y/n) ")
    if repeat != 'y':               # 不是輸入y,則離開while迴圈
        market_survey = False

# 市場調查結束
print("\n\n以下是市場調查的結果")
for user, location in survey_dict.items( ):
    print(user, "夢幻旅遊景點: ", location)