# -*- coding: utf-8 -*-
"""loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYN_9DG1zKX07tj5TuYN9neP-0VVvZ6_

#<b> <font color='blue'>吳南烈 迴圈作業

#<b>練習01: while loop

<b>輸入整數N，並輸出1,2,3,…,N。
"""

n = int(input('輸入整數N:'))
c = 1
while c < n:
  print(c, end=', ')
  c+=1
else:
  print () #換列
  print(c)

"""#<b>練習02:  while loop

<b>輸入N，並輸出N, N-1,…, 3, 2, 1。
"""

n = int(input('輸入整數N:'))
while n > 1:
  print(n, end=', ')
  n-=1  
else:
  print(n)

"""#<b>練習03: for loop

<b>輸入N，並輸出1,2,3,…,N。
"""

n=int(input('輸入整數N: '))
for i in range(1,n): #1,2,3,...9
  print(i, end=', ')
else:
  print()
  print(i+1) #最後被印出的數

"""#<b>練習04:   巢狀迴圈結構 (nested loop)

<b>輸入正整數 M，重複輸出M列，每列包含M個*。
"""

M = int(input('輸入方陣邊長: '))
for x in range(M):  
  print("第{}列: ".format(x+1), end=" ")
  for y in range(M):
    print('*', end=' ')
  else:
    print() #每列結束換行

"""#<b>練習05:  迴圈中斷 (break)

<b>A小姐每天都會運動，並輸入每天的BMI值，她計畫持續運動直到BMI小於25。
"""

while True:
  print("持續運動..", end=" ")
  bmi = float(input("請輸入目前BMI:"))
  if bmi < 25:
    print("體脂肪達標")
    break

"""#<b>問題1

<b>請使用迴圈敍述撰寫一程式，讓使用者輸入兩個正整數a、b(a<b)，利用迴圈計算從a 開始連續加到b，計算其總和。例如:輸入a=1、b=100，則輸出結果為5050(1+2+...100=5050)

輸入: 兩個正整數 (a、b，且 a<b) <br>
輸出: 計算從a 開始連加到b的總和
"""

# 簡易迴圈 ,例如:輸入a=1、b=100，則輸出結果為5050(1+2+...100=5050)
a=int(input("輸入a:"))
b=int(input("輸入b:"))
ans=0   #先將答案設為0

for i in range(a,b+1):
  print(i,end=' ')
  ans+=i
print("答案為:",ans)

"""#<b>問題2

<b>
請使用迴圈敍述撰寫一程式，讓使用者輸入一個正整數(<100)，然後以三角形的方式依序輸出此數的階乘結果

輸入: 一個正整數 (<100) <br>
輸出: 以三角形的方式依序輸出此數的階乘結果
"""

# 巢狀迴圈
num=eval(input("輸入一小於100正整數:"))
for i in range(1,num+1):
  for j in range(1,i+1):
    print("%4d"%(i+j),end='')
  print()

"""#<b>問題3

<mark><b>請使用迴圈敍述撰寫一程式，讓使用者輸入一個正整數a，利用迴圈計算從1到 a之間，所有 5之倍數數字總和 </mark>

輸入: 一個正整數 <br>
輸出: 所有5之倍數數字總和
"""

# 迴圈倍數總和
num=eval(input("輸入一正整數:"))
ans=0;    # ans歸0
for i in range(1,num+1):
  if i%5==0:
    ans+=i  #ans=ans+1
print("ans=",ans)